# Copyright (c) 2024, Itential, Inc
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
---
- name: Include tasks to validate variables
  ansible.builtin.include_tasks:
    file: validate-vars.yml
  tags: always

- name: Install and configure Redis
  notify:
    - Enable and Start Redis
    - Enable and Start Redis Sentinel
  block:
    - name: Install Redis
      tags: install_redis
      notify: Update Itential release file
      block:
        - name: Include common installation tasks
          ansible.builtin.include_tasks:
            file: install-common.yml

        - name: Include tasks to perform online installation
          when: not offline_install_enabled
          block:
            - name: Include tasks to install Redis using source
              ansible.builtin.include_tasks:
                file: install-from-source.yml
              when: redis_install_from_source | bool

            - name: Include tasks to install Redis using repo
              ansible.builtin.include_tasks:
                file: install-from-repo.yml
              when: not redis_install_from_source | bool

        - name: Include tasks to perform offline installation
          ansible.builtin.include_tasks:
            file: install-offline.yml
          when: offline_install_enabled

    - name: Configure SELinux
      tags: configure_selinux
      block:
        - name: Include tasks to configure SELinux
          ansible.builtin.include_tasks:
            file: configure-selinux.yml
          when:
            - ansible_selinux.status == "enabled"
            - redis_install_from_source | bool

    - name: Configure Redis/Sentinel
      tags: configure_redis
      block:
        - name: Include tasks to configure Redis
          ansible.builtin.include_tasks:
            file: configure-redis.yml

        - name: Include tasks to configure Sentinel
          ansible.builtin.include_tasks:
            file: configure-sentinel.yml
          when: redis_replication_enabled | bool

- name: Ensure Redis is running
  tags: always
  block:
    - name: Flush all handlers
      ansible.builtin.meta: flush_handlers

    - name: Start Redis
      ansible.builtin.systemd:
        name: redis
        state: started

    - name: Assert that Redis is running
      block:
        - name: Get Redis service status
          ansible.builtin.systemd:
            name: redis
          register: redis_status

        - name: Assert that Redis is running
          ansible.builtin.assert:
            that: redis_status.status.ActiveState == "active"
            fail_msg: "Redis service is not running (state: {{ redis_status.status.ActiveState }})"
            success_msg: "Redis service is running correctly"

- name: Ensure Sentinel is running
  when: redis_replication_enabled | bool
  tags: always
  block:
    - name: Start Sentinel
      ansible.builtin.systemd:
        name: redis-sentinel
        state: started

    - name: Assert that Sentinel is running
      block:
        - name: Get Sentinel service status
          ansible.builtin.systemd:
            name: redis-sentinel
          register: redis_sentinel_status

        - name: Assert that Sentinel is running
          ansible.builtin.assert:
            that: redis_sentinel_status.status.ActiveState == "active"
            fail_msg: "Sentinel service is not running (state: {{ redis_sentinel_status.status.ActiveState }})"
            success_msg: "Sentinel service is running correctly"
