name: Test Deployer

on:
  push:
    branches:
      - pipeline-test

env:
  TF_DIRECTORY: ./tofu_aws
  ANSIBLE_HOST_KEY_CHECKING: "False"

jobs:
  test-deployer:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set design parameter
      id: design
      run: echo "design=aio" >> $GITHUB_OUTPUT

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: latest

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Install this collection
      run: ansible-galaxy collection install .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

    - name: Setup SSH for GitLab
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
        
    - name: Clone Themis repository
      run: |
        git clone "${{ secrets.THEMIS_REPO_SSH_STRING }}" ~/themis
        cd ~/themis
        ls -la

    - name: Initialize OpenTofu
      working-directory: /home/runner/themis/tofu_aws
      run: tofu init

    - name: Provision EC2 instances for Minimal design
      working-directory: /home/runner/themis/tofu_aws
      run: tofu apply -var-file=tfvars/minimal.tfvars -auto-approve

    - name: Generate Ansible inventory hosts file
      working-directory: /home/runner/themis/tofu_aws
      run: python3 ../scripts/generate_inventory.py --platform-release 6.0 --platform-packages itential-platform-6.0.7-1.noarch.rpm --gateway-release 2023.1 --gateway-whl-file automation_gateway-3.227.0+2023.1.9-py3-none-any.whl -o hosts.json

    - name: Wait for EC2 instances to be ready
      working-directory: /home/runner/themis/tofu_aws
      run: sleep 60s

    - name: Run deployer on created instances
      run: ansible-playbook itential.deployer.site -i /home/runner/themis/tofu_aws/hosts.json -v

    - name: Tear down EC2 instances
      working-directory: /home/runner/themis/tofu_aws
      run: tofu destroy -var-file=tfvars/minimal.tfvars -auto-approve
