name: Test Deployer on Pull Request


on:
  #pull_request:
  push:
    branches:
      - main


jobs:
  #generate-test-cases:
  #  runs-on: ubuntu-latest
  #  strategy:
  #    matrix:
  #      design: [aio, minimal, ha2, asa]
  #    fail-fast: true
  #  steps:
  #    - name: Set output design
  #      id: set-output
  #      run: echo "design=${{ matrix.design }}" >> $GITHUB_OUTPUT

  run-tests:
    uses: ./.github/workflows/test-deployer.yml
    with:
      design: minimal
    secrets: inherit
