name: Test Deployer on Pull Request


on:
  #pull_request:
  push:
    branches:
      - main


jobs:
  generate-test-cases:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        design: [aio, minimal, ha2, asa]
      fail-fast: true

  run-tests:
    needs: generate-test-cases
    uses: ./.github/workflows/test-deployer.yml
    with:
      design: ${{ needs.generate-test-cases.outputs.design }}
    secrets: inherit
