name: Test Deployer on Pull Request


on:
  push:
    branches:
      - pipeline-test


jobs:
  run-tests:
    strategy:
      matrix:
        design: [aio, minimal, ha2, asa]
    uses: ./.github/workflows/test-deployer.yml
    with:
      design: ${{ matrix.design }}
    secrets: inherit
