name: Test Deployer

on:
  push:
    branches:
      - pipeline-test

env:
  TF_DIRECTORY: ./tofu_aws
  ANSIBLE_HOST_KEY_CHECKING: "False"

jobs:
  test-deployer:
    runs-on: self-hosted
    timeout-minutes: 60
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    #- name: Setup Python
    #  uses: actions/setup-python@v4
    #  with:
    #    python-version: '3.11'

    - name: Install dnf packages
      run: |
        sudo dnf groupinstall 'Development Tools' -y
        sudo dnf install python3-pip -y
        sudo dnf install nodejs -y

    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: latest

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Install this collection
      run: ansible-galaxy collection install . --force

    - name: Download Platform and Gateway binaries
      run: |
        cd ~/.ansible/collections/ansible_collections/itential/deployer/playbooks
        mkdir -p files
        cd files
        ${{ secrets.PLATFORM_RPM_DOWNLOAD_COMMAND }}
        ${{ secrets.GATEWAY_WHL_DOWNLOAD_COMMAND }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

    - name: Setup SSH for GitLab and EC2
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/pet-east1.open.pem
        chmod 600 ~/.ssh/id_rsa
        chmod 600 ~/.ssh/pet-east1.open.pem
        ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
        
    - name: Clone Themis repository
      working-directory: ".."
      run: |
        rm -rf themis
        git clone "${{ secrets.THEMIS_REPO_SSH_STRING }}"
        cd themis
        ls -la

    - name: Initialize OpenTofu
      working-directory: ../themis/tofu_aws
      run: tofu init

    - name: Provision EC2 instances for Minimal design
      working-directory: ../themis/tofu_aws
      run: tofu apply -var-file=tfvars/minimal.tfvars -auto-approve

    - name: Generate Ansible inventory hosts file
      working-directory: ../themis/tofu_aws
      run: python3 ../scripts/generate_inventory.py -o hosts.json

    - name: Create Ansible playbook to wait for EC2 instances to be ready
      working-directory: ../themis/tofu_aws
      run: |
        cat > wait-for-instances.yml << 'EOF'
        ---
        - name: Wait for instances to initialize
          hosts: all
          gather_facts: no
          become: no
          serial: "{{ ansible_serial | default(10) }}"
          
          vars:
            ssh_port: 22
            
          tasks:
            - name: Wait for SSH connection to be ready
              ansible.builtin.wait_for_connection:
                delay: 10
                timeout: 60
              
            - name: Wait for cloud-init to complete (marker file check)
              ansible.builtin.wait_for:
                path: /var/log/cloud-init-finished.marker
                timeout: 60
              become: yes
        EOF
        
    - name: Wait for EC2 instances to be ready
      working-directory: ../themis
      run: ansible-playbook wait-for-instances.yml -i tofu_aws/hosts.json -i inventories/common -i inventories/minimal -v --key-file=~/.ssh/pet-east1.open.pem

    - name: Run deployer on created instances
      working-directory: ../themis
      env:
        ANSIBLE_HOST_KEY_CHECKING: "False"
      run: ansible-playbook itential.deployer.site -i tofu_aws/hosts.json -i inventories/common -i inventories/minimal -v --key-file=~/.ssh/pet-east1.open.pem

    - name: Tear down EC2 instances
      if: always()
      working-directory: ../themis/tofu_aws
      run: tofu destroy -var-file=tfvars/minimal.tfvars -auto-approve
