name: Test Deployer

on:
  push:
    branches:
      - pipeline-test

env:
  TF_DIRECTORY: ./tofu_aws
  ANSIBLE_HOST_KEY_CHECKING: "False"

jobs:
  test-deployer:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set design parameter
      id: design
      run: echo "design=aio" >> $GITHUB_OUTPUT

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: latest

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
        ansible-galaxy collection install itential.deployer

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION || 'us-east-1' }}

    - name: Setup SSH for GitLab
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H gitlab.com >> ~/.ssh/known_hosts
        
    - name: Clone Themis repository
      run: |
        git clone "${{ secrets.THEMIS_REPO_SSH_STRING }}" ~/themis
        cd ~/themis
        ls -la
