name: Test Deployer on Pull Request


on:
  push:
    branches:
      - pipeline-test


jobs:
  run-test:
    strategy:
      matrix:
        design: [minimal]
        os-type: [rocky, rhel]
        os-version: ["8", "9"]
      fail-fast: true
    uses: ./.github/workflows/test-deployer.yml
    with:
      design: ${{ matrix.design }}
      os-type: ${{ matrix.os-type }}
      os-version: ${{ matrix.os-version }}
    secrets: inherit
