name: Test Deployer on Pull Request


on:
  push:
    branches:
      - pipeline-test


jobs:
  run-test:
    strategy:
      matrix:
        design: [aio, minimal, ha2, asa]
        os-type: [rocky, rhel]
        os-version: [8, 9]
      fail-fast: false
    uses: ./.github/workflows/test-deployer.yml
    with:
      design: ${{ matrix.design }}
      os-type: rocky
      os-version: "9"
    secrets: inherit
